/**
 * NeighbourNet — Mock data.
 *
 * Used only as a fallback / storybook reference.
 * The live dashboard now sources data from useMessages (GET /api/messages).
 * These objects must satisfy the full Message interface.
 */

import { Message, MeshStatus } from './types';

export const mockMessages: Message[] = [
  {
    message_id: 'msg-001',
    body: 'আমরা আটকা পড়েছি, নৌকা দরকার. Water rising very fast.',
    sender_id: 'NODE-74A2',
    gps_lat: 22.352,
    gps_lng: 88.854,
    location_hint: 'Gosaba North',
    priority_score: 0.96,
    priority_tier: 'CRITICAL',
    cloud_priority_tier: null,
    triage_summary: null,
    extracted_location: null,
    ttl: 7,
    hop_count: 3,
    created_at: new Date(Date.now() - 120000).toISOString(),
    last_hop_at: new Date(Date.now() - 5000).toISOString(),
    synced: true,
    acknowledged: false,
    acknowledged_at: null,
  },
  {
    message_id: 'msg-002',
    body: 'Medical emergency, 2 elderly stuck on roof.',
    sender_id: 'NODE-39B1',
    gps_lat: 22.684,
    gps_lng: 88.868,
    location_hint: 'Basirhat East',
    priority_score: 0.92,
    priority_tier: 'CRITICAL',
    cloud_priority_tier: 'CRITICAL',
    triage_summary: 'Two elderly persons stranded on rooftop, immediate evacuation needed.',
    extracted_location: 'Basirhat East, North 24 Parganas',
    ttl: 5,
    hop_count: 5,
    created_at: new Date(Date.now() - 250000).toISOString(),
    last_hop_at: new Date(Date.now() - 15000).toISOString(),
    synced: true,
    acknowledged: false,
    acknowledged_at: null,
  },
  {
    message_id: 'msg-003',
    body: 'Need food and drinking water for 15 families.',
    sender_id: 'NODE-11C4',
    gps_lat: 22.742,
    gps_lng: 88.942,
    location_hint: 'Hasnabad',
    priority_score: 0.81,
    priority_tier: 'HIGH',
    cloud_priority_tier: 'HIGH',
    triage_summary: 'Food and water required for 15 families within 24 hours.',
    extracted_location: null,
    ttl: 8,
    hop_count: 2,
    created_at: new Date(Date.now() - 400000).toISOString(),
    last_hop_at: new Date(Date.now() - 20000).toISOString(),
    synced: true,
    acknowledged: false,
    acknowledged_at: null,
  },
  {
    message_id: 'msg-004',
    body: 'Cell tower down, using mesh to report flooding.',
    sender_id: 'NODE-88D9',
    gps_lat: 22.583,
    gps_lng: 88.756,
    location_hint: 'Minakhan',
    priority_score: 0.76,
    priority_tier: 'HIGH',
    cloud_priority_tier: null,
    triage_summary: null,
    extracted_location: null,
    ttl: 6,
    hop_count: 4,
    created_at: new Date(Date.now() - 500000).toISOString(),
    last_hop_at: new Date(Date.now() - 45000).toISOString(),
    synced: true,
    acknowledged: false,
    acknowledged_at: null,
  },
  {
    message_id: 'msg-005',
    body: 'Road blocked by fallen trees, access to highway cut.',
    sender_id: 'NODE-22E5',
    gps_lat: 22.766,
    gps_lng: 88.225,
    location_hint: 'Namkhana Route',
    priority_score: 0.55,
    priority_tier: 'MEDIUM',
    cloud_priority_tier: null,
    triage_summary: null,
    extracted_location: null,
    ttl: 9,
    hop_count: 1,
    created_at: new Date(Date.now() - 900000).toISOString(),
    last_hop_at: new Date(Date.now() - 60000).toISOString(),
    synced: true,
    acknowledged: false,
    acknowledged_at: null,
  },
  {
    message_id: 'msg-006',
    body: 'Testing mesh node connectivity post-rain.',
    sender_id: 'NODE-44F8',
    gps_lat: 22.421,
    gps_lng: 88.632,
    location_hint: 'Canning Center',
    priority_score: 0.22,
    priority_tier: 'LOW',
    cloud_priority_tier: 'LOW',
    triage_summary: null,
    extracted_location: null,
    ttl: 10,
    hop_count: 1,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    last_hop_at: new Date(Date.now() - 3600000).toISOString(),
    synced: true,
    acknowledged: true,
    acknowledged_at: new Date(Date.now() - 1800000).toISOString(),
  },
];

export const initialMeshStatus: MeshStatus = {
  active_nodes: 0,
  queue_depth: 0,
  gateways: [],
  last_sync_at: new Date().toISOString(),
  has_active_gateways: false,
};
